######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 25 22:10:41 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += webkit

# Input
HEADERS += mazescene.h
SOURCES += main.cpp mazescene.cpp
